### ISSUE TITLE
quickly clicking twice on QSpinBox maximizes the window

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#12] opened 2015-06-10 23:36 UTC
Using IceMW on Ubuntu 14.04.

1) Double-clicking on the app background (any of the grey area) maximizes the app.  I'm not wild about this behaviour, since other Qt apps don't seem to act this way, but I'm not complaining about this.  (note: normally in IceWM, double-clicking the title bar maximizes the window.  This is also working in tarsnap-gui, and I have no complaints about this)

2) however, clicking twice on arrows in a QSpinBox (such as Settings->App->Skip files larger than) also maximizes the window.  This is not good behaviour.

Obviously the click-event is not stopping in the QSpinBox; it gets passed up the chain through the various QWidgets, QMainWindow, and finally to the window manager.

**Comment by shinnok** [comment] 2015-06-11 03:07
No.2 sounds like a bug with Qt on that WM.

Doesn't reproduce on OS X. I'll test the other platforms in regards to it.

PS: append the Qt version to reports that might have something to do with it.

**Comment by gperciva** [comment] 2015-06-11 05:07
I'm on Qt 5.2.1.

Can you reproduce this?
1. slowly click up or down on the "skip files larger than" => nothing printed on console.
2. quickly double-click on up or down => this is printed on the console:

     src/widgets/mainwindow.cpp(526): COMMIT SETTINGS

I'm not saying that "commit settings" is necessarily a problem, but it's suspicious that this happens with a double-click but not with two single-clicks.

**Comment by gperciva** [comment] 2015-06-11 05:15
wait a moment, now I'm massively confused.

    src/widgets/mainwindow.cpp

line 259 (and up) is this:

    void MainWindow::mouseDoubleClickEvent(QMouseEvent *event)
    {
        Q_UNUSED(event);
        if(isMaximized())
            this->showNormal();
        else
            this->showMaximized();
    }

I added a

        printf("MainWindow::mouseDoubleClickEvent\n");

to that.  Doing the normal double-click on QSpinBox, I see:

    MainWindow::mouseDoubleClickEvent
    src/widgets/mainwindow.cpp(527): COMMIT SETTINGS

If you add the same debug line of code and do the double-click, doesn't your system print the DoubleClickEvent line?

**Comment by shinnok** [comment] 2015-06-12 06:45
Really, I can't reproduce this on OS X. The double click on any empty surface area of the MainWindow to maximize is on purpose, but it wouldn't affect any child widget unless there's a bug of course.

Do you have anything else besides IceWM on your system? Maybe switch to a different one for a bit and reproduce your steps there. That's the only way you can bisect this into either application behavior or desktop/Qt behavior.

**Comment by gperciva** [comment] 2015-06-12 07:02
1) why maximize on empty-space double-click?  That's not how normal applications work.  Why introduce that surprise?

2) Yes, it still generate a mouseDoubleClickEvent SIGNAL which is picked up by MainWindow even if I use the default Ubuntu window manager.

**Comment by shinnok** [comment] 2015-06-12 07:08
I just fired up an Ubuntu VM and it doesn't reproduce there either.

**Comment by shinnok** [comment] 2015-06-15 10:16
I tested this on Ubuntu 14.04.2 Unity. It does reproduce there and this happens with rapid clicking:
1. The spinbox is being disabled and loses focus for a split second; (that also explains the COMMIT SETTINGS message)
2. The mouse events are then passed to the parent mainwindow;
3. If two of those are being sent in succession, Qt will fire mouseDoubleClickEvent and thus be handled by the maximize/restore code;

This looks like a bug in the older version of Qt in 14.04 or WM or both. This doesn't reproduce on 15.04 anymore. Searching for this on https://bugreports.qt.io didn't yield results.

**Comment by shinnok** [comment] 2015-06-29 13:27
Since this is a side-effect on our part and a bug in Qt/WM I don't see much reason in disabling the double click functionality until there's at least one extra complaint against this.

Closing this until then.

**Closed by shinnok** 2015-06-29 13:27 UTC
Labels: bug
